name: Build&Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.19.x
    - name: Install dependencies
      run: npm ci
    - name: Build Lib
      run: npm run build-lib
    - name: Build Example
      run: npm run build-example

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.19.x
    - name: Install dependencies
      run: npm ci
    - name: Test Library
      run: npm run test-lib

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.19.x
    - name: Install dependencies
      run: npm ci
    - name: Run Lint
      run: npm run lint-lib