name: NPM Publish

on:
  release:
    types: [created]

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Test Library
        run: npm run test-lib
      - name: Build Library
        run: npm run build-lib
      - name: Publish Library
        run: npm publish
        working-directory: ./dist/angular-mydatepicker
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
